### ISSUE TITLE
Dropdown width isn't responsive.

### ISSUE THREAD

**Issue by mineblock11** [modrinth/omorphia#38]
I assumed the dropdown would be responsive. If it's intentionally not responsive just close this issue.

<hr />

![](https://i.imgur.com/loT7VR3.gif)

**Comment by mineblock11** [comment]
Workaround: Use `display: flex` on the parent div and enable flex grow.

```css
.animated-dropdown {
  flex-grow: 1;
}

.element-that-contains-dropdown {
  display: flex;
}
```
